###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Test thêm chi tiết hàng hóa
POST http://localhost:5000/api/chitiethanghoa/insert
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzgxODRkNzgwYjk4NTQwMjBjNTUzMzUiLCJpYXQiOjE2Njk0NTY0MDl9.036oHLeojIvBKhCLhzFjcEtE65syT8yWO2_XedLZp0E

{
  "tenhang":"Cần có dữ liệu mẫu 2",
  "soluong": 10,
  "dongiaFOB":1000,
  "tygiaUSD":2400,
  "dongiakho":0,
  //thanhtiengiakho, //cần tính
  "dongiaban":1500,
  //thanhtiengiaban, //cần tính
  "baohanh":true,
  "ghichu":"Còn thiếu Tổng tiền nhập kho và bán của hàng hóa"
}

###test get chiphithubaolanh

GET http://localhost:5000/api/chitiethanghoa
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzgxODRkNzgwYjk4NTQwMjBjNTUzMzUiLCJpYXQiOjE2Njk0NDkwMzV9.WM0Yz7-o1iFx-X2FEySuB3cgHdp1rsoqHlbObS6sPeM
###

PUT http://localhost:5000/api/chitiethanghoa/6381c64a89943c5b0c4f2a7e
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzgxODRkNzgwYjk4NTQwMjBjNTUzMzUiLCJpYXQiOjE2Njk0NDkwMzV9.WM0Yz7-o1iFx-X2FEySuB3cgHdp1rsoqHlbObS6sPeM

{
  "tenhang":"Cần có dữ liệu mẫu CẬP NHẬT",
  "soluong": 2,
  "dongiaFOB":1000,
  "dongiakho":1200,
  //thanhtiengiakho, //cần tính
  "dongiaban":1500,
  //thanhtiengiaban, //cần tính
  "ghichu":"Còn thiếu Tổng tiền nhập kho và bán của hàng hóa"
}

###

DELETE http://localhost:5000/api/chitiethanghoa/6381c56089943c5b0c4f2a73
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzgxODRkNzgwYjk4NTQwMjBjNTUzMzUiLCJpYXQiOjE2Njk0NDkwMzV9.WM0Yz7-o1iFx-X2FEySuB3cgHdp1rsoqHlbObS6sPeM


