### ok 
### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Create MandayCost
### access Public
### Not 
POST http://localhost:5000/api/forms/capital-expenditure-cost/post
Content-Type: application/json
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5MDM1OSwiZXhwIjoxNjcxMzc2NzU5fQ.4WKjVO2EpJrYhAs9L38YaB4kl-P6t4D58HbDDOUXMCU

{
  "InventoryDays": 60,
  "ImplementationDays": 20,
  "BedtDays": 20,
  "DebtCollectionDays": 15, 
  "Note": "A",
  "ContractID":"HD02"
}


### Get all MandayCost
### access public
###ok
GET http://localhost:5000/api/forms/capital-expenditure-cost
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ

### Get MandayCost by id
### access public
###ok
GET http://localhost:5000/api/forms/capital-expenditure-cost/63b895ad315c46311dd16704
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ


### update MandayCost
### access Public
###  
PUT http://localhost:5000/api/forms/capital-expenditure-cost/put/63b8e868165f143e28359fb4
Content-Type: application/json
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5MDM1OSwiZXhwIjoxNjcxMzc2NzU5fQ.4WKjVO2EpJrYhAs9L38YaB4kl-P6t4D58HbDDOUXMCU

{
  "InventoryDays": 60,
  "ImplementationDays": 20,
  "BedtDays": 20,
  "DebtCollectionDays": 15, 
  "Note": "A",
  "ContractID":"HD02"
}


### Get all Contract tạo bởi user đăng nhập
### access public
###ok
DELETE  http://localhost:5000/api/forms/capital-expenditure-cost/delete/63b89b2d42f44137d960dafd
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ
