### ok 
### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}
### Create Contract
### access Public
### Not ok -- Postman ok
POST http://localhost:5000/api/forms/contract/post
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzA4YmM3MzA4NmJmYmIzNDQxZDNlNCIsImlhdCI6MTY3MzY0ODE0NywiZXhwIjoxNjczNjU0NTQ3fQ.e7bSXaAZGfrqg-k30qYVAYd4efQb43Z9ln8J6S2lFno

{
"Center": "HCM",
"Deparment": "SSD",
"CustomerID": "A",
"ContractID": "HD02",
"Date": "2022-12-14T17:00:00.000Z"
//"user": "admin"
}

### Get all Contract 
### access private
###ok
GET http://localhost:5000/api/forms/contract
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTQ1MjE5MywiZXhwIjoxNjcxNTM4NTkzfQ.G-Vxj5c1EuoFUzQnggRb7BbxyUc1V6eu95PtglyUOz0

### Get Contract by id
### access public
###ok
GET http://localhost:5000/api/forms/contract/63a5584e804f6122468105c5
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTQ1MjE5MywiZXhwIjoxNjcxNTM4NTkzfQ.G-Vxj5c1EuoFUzQnggRb7BbxyUc1V6eu95PtglyUOz0



### Update Contract
### access Public
### ok -- Postman ok
PUT http://localhost:5000/api/forms/contract/put/63a5584e804f6122468105c5
Content-Type: application/json
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhmMTgyNTkxNWQzZjQxZTQ1ZDIyOWUiLCJpYXQiOjE2NzAzMjMwMDd9.2LnfC9zLc42tocLoZGxyVrFMW4xGH_mOpRwusDoriq4

{
  "Center": "HSI update REST",
  "Deparment": "SSD1",
  "CustomerID": "A",
  "ContractID": "HD01",
  "Date": "2022-12-14T17:00:00.000Z"
}

###

DELETE http://localhost:5000/api/forms/contract/delete/63a4dff562d2de8060a07f6f
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5MDM1OSwiZXhwIjoxNjcxMzc2NzU5fQ.4WKjVO2EpJrYhAs9L38YaB4kl-P6t4D58HbDDOUXMCU
