### ok 
### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Create MandayCost
### access Public
### Not 
POST http://localhost:5000/api/forms/manday-cost/post
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjIzNmVkYWFlNTA5NGNkN2YxZWU4MyIsImlhdCI6MTY3MjcwMDEyNywiZXhwIjoxNjcyNzA2NTI3fQ.0XLpjB0WhYn_D8qU12tZy3DsUKweDLxd2GYJveCCFJk

{
"RatioUSD": 24000,
"Department": "Phòng GP An Toàn TT",
"Cost": 60,
"StaffNumber": 1,
"ImplementationDay": 15,
"Note": "HD03",
"ContractID":"HD03"
}


### Get all MandayCost
### access public
###ok
GET http://localhost:5000/api/forms/manday-cost
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ

### Get MandayCost by idMandaycost
### access public
###ok
GET http://localhost:5000/api/forms/manday-cost/63a54823564e1d18b4bc1cd5
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ

### Get MandayCost by idcontract
### access public
###ok
GET http://localhost:5000/api/forms/manday-cost/contract/63c08c08b1a40f0ce190d6e1
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ


### update MandayCost
### access Public
###  
PUT http://localhost:5000/api/forms/manday-cost/put/63a54823564e1d18b4bc1cd5
Content-Type: application/json
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5MDM1OSwiZXhwIjoxNjcxMzc2NzU5fQ.4WKjVO2EpJrYhAs9L38YaB4kl-P6t4D58HbDDOUXMCU

{
"RatioUSD": 24000,
"Department": "Phòng GP An Toàn TT Update",
"Cost": 60,
"StaffNumber": 1,
"ImplementationDay": 15,
"Note": "A",
"ContractID":"HD01"
}


### Get all Contract tạo bởi user đăng nhập
### access public
###ok
DELETE  http://localhost:5000/api/forms/manday-cost/delete/63a54823564e1d18b4bc1cd5
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ
