### ok 
### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Create GuaranteeLetterCost
### access Public
### Not 
POST http://localhost:5000/api/forms/Guarantee-letter-cost/post
Content-Type: application/json
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5MDM1OSwiZXhwIjoxNjcxMzc2NzU5fQ.4WKjVO2EpJrYhAs9L38YaB4kl-P6t4D58HbDDOUXMCU

{
"Content": "BL dự thầu",
"Cost": "360000000",
"QuantityMonths": 3,
"RatioCost": 0.2,
//"IntoMoney": 0, //thanh tien =  Cost*RatioCost
"Note": "Tính cả phần nhờ hỗ trợ",
"ContractID":"HD01"
}

### Get all GuaranteeLetterCost
### access public
###ok
GET http://localhost:5000/api/forms/Guarantee-letter-cost
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYTgxNTE2Mzk0ZTAyODg4YjQ1NTBiMCIsImlhdCI6MTY3MjA5NjQ2OSwiZXhwIjoxNjcyMTgyODY5fQ.GevAk4e-IENktSuRMHXDtZa4tfe4WlYvYt2mF48RJZU
### Get GuaranteeLetterCost by id
### access public
###ok
GET http://localhost:5000/api/forms/Guarantee-letter-cost/63a54f26e68b441c2566bdd7
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ


### Create GuaranteeLetterCost
### access Public
### Not 
PUT http://localhost:5000/api/forms/Guarantee-letter-cost/put/63a54f26e68b441c2566bdd7
Content-Type: application/json
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5MDM1OSwiZXhwIjoxNjcxMzc2NzU5fQ.4WKjVO2EpJrYhAs9L38YaB4kl-P6t4D58HbDDOUXMCU

{
"Content": "BL dự thầu Update ",
"Cost": "370000000",
"QuantityMonths": 3,
"RatioCost": 0.2,
//"IntoMoney": 0, //thanh tien =  Cost * RatioCost
"Note": "Tính cả phần nhờ hỗ trợ",
"ContractID":"HD01"
}


### Delete GuaranteeLetterCost
### access Public
###ok
DELETE  http://localhost:5000/api/forms/Guarantee-letter-cost/delete/63a54f26e68b441c2566bdd7
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ
