### ok 
### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Get all Contract 
### API access: /api/forms/contract
### Test: ok
//GET http://103.88.121.45:5000/api/forms/contract
GET http://localhost:5000/api/forms/contract

### 
//Khoi tao Implementation_Cost: TÊN DANH MỤC voi idcontract
// @access Public
POST http://localhost:5000/api/forms/implementation_category/post/
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzA4YmM3MzA4NmJmYmIzNDQxZDNlNCIsImlhdCI6MTY3NjQyMzQyNiwiZXhwIjoxNjc2NDI5ODI2fQ.9Y5N7ih0MbzecX_uwy4bMqf0Di3LLFJGMJkqLiqre-U

{
  "idcontract": "64042be3272b3022644b428f",
  "Category": "GIAI DOAN TRIEN KHAI",
  "StagesImplementation": "Giai đoạn 1"
}

### 
//CAP NHAT TÊN DANH MỤC voi idImplementation_Cost
// @access Public
//PUT http://localhost:5000/api/forms/implementation_category/put/641183defa83ebd0141e9b41
PUT http://localhost:5000/api/forms/implementation_category/put/641183defa83ebd0141e9b41
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzA4YmM3MzA4NmJmYmIzNDQxZDNlNCIsImlhdCI6MTY3NjQyMzQyNiwiZXhwIjoxNjc2NDI5ODI2fQ.9Y5N7ih0MbzecX_uwy4bMqf0Di3LLFJGMJkqLiqre-U

{
  "Category": "CHI PHÍ CHUNG UPDATE 77777"
}

### 
//XOA DANH MỤC voi idImplementation_Cost
// @access Public  http://localhost:5000/api/forms/implementation_category/delete/:id_danh_muc
DELETE  http://localhost:5000/api/forms/implementation_category/delete/641149eeee229bcdd96e680e
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzA4YmM3MzA4NmJmYmIzNDQxZDNlNCIsImlhdCI6MTY3NjQyMzQyNiwiZXhwIjoxNjc2NDI5ODI2fQ.9Y5N7ih0MbzecX_uwy4bMqf0Di3LLFJGMJkqLiqre-U

### Get ImplementationCost by idcontract
### API access: /api/forms/implementation-cost/:idcontract
### Test: ok
GET http://localhost:5000/api/forms/implementations/64042be3272b3022644b428f

### Get all ImplementationCost by idcontract
### API access: /api/forms/implementation-cost/:idcontract
### Test: ok
GET http://localhost:5000/api/forms/implementations/

### Them 1 giai doan chi phi 
// API access: 
// Test: 
POST http://localhost:5000/api/forms/implementations/stages_implementation/post/
Content-Type: application/json
//Authorization: admin admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzA4YmM3MzA4NmJmYmIzNDQxZDNlNCIsImlhdCI6MTY3NTczNTAxMCwiZXhwIjoxNjc1NzQxNDEwfQ.scN6d8whKvzWwl0G95cQteITNug2BTj-aQ61GqypF_0

{
  "idImplementation_Cost": "641183defa83ebd0141e9b41",
  "Content": "GIAI DOAN 2"
}

### CAP NHAT TEN giai doan chi phi voi   :idImplementationCost/:idContentCost
// API access: http://localhost:5000/api/forms/implementations/stages_implementation/put/:idImplementationCost/:idContentCost
// Test: OK
PUT http://localhost:5000/api/forms/implementations/stages_implementation/put/64108c9f40f26fb85aee07e4/64108c9f40f26fb85aee07e5
Content-Type: application/json
//Authorization: admin admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzA4YmM3MzA4NmJmYmIzNDQxZDNlNCIsImlhdCI6MTY3NTczNTAxMCwiZXhwIjoxNjc1NzQxNDEwfQ.scN6d8whKvzWwl0G95cQteITNug2BTj-aQ61GqypF_0

{
  "Content": "GIAI DOAN 1"
}

### XOA giai doan chi phi voi   :idImplementationCost/:idContentCost
// API access: http://localhost:5000/api/forms/implementations/stages_implementation/delete/:idImplementationCost/:idContentCost
// Test: OK
DELETE  http://localhost:5000/api/forms/implementations/stages_implementation/delete/641183defa83ebd0141e9b41/6411aef4fa83ebd0141e9b9f
Content-Type: application/json
//Authorization: admin admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzA4YmM3MzA4NmJmYmIzNDQxZDNlNCIsImlhdCI6MTY3NTczNTAxMCwiZXhwIjoxNjc1NzQxNDEwfQ.scN6d8whKvzWwl0G95cQteITNug2BTj-aQ61GqypF_0

### Test: ok
GET http://localhost:5000/api/forms/implementations/640d3565451dad4ca167827c


### Them 1 chi phi vao giai doan chi phi trien khai
// API access: /api/forms/implementation-cost/stages-implementation/post/:idImplementationCost/:idContentCost
// Test: ok

POST http://localhost:5000/api/forms/implementations/stages_implementation/CostDetail/post
Content-Type: application/json
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzA5MzhmZWQ2MGYxMTUyMWIwMDg3NSIsImlhdCI6MTY3MzgzMDMwMywiZXhwIjoxNjczODM2NzAzfQ.rCcG8J8svtJelTkt1GOAotImXWm43P7ES4l1OosEElI

{
  "NameCost": "Chi phí TRIEN KHAI 2",
  "Units": "Phong",
  "UnitPrice": 2000000,
  "Quantity_days": 1,
  "Quantity_times": 4,
  "IntoMoney": 0,
  "Note": "",
  "Implementation_Cost_Id": "641321143f276b087cf0bdbe",
  "ContentCostId": "641321143f276b087cf0bdbf"
}
### Test: ok
GET http://localhost:5000/api/forms/implementations/640d3565451dad4ca167827c


### CAP NHAT 1 chi phi trong giai doan chi phi TRIEN KHAI
// API access: /api/forms/implementation-cost/stages-implementation/cost/put/
// Test: OK
//Note: Cap nhat xong  idCost bi thay doi !
PUT http://localhost:5000/api/forms/implementations/stages_implementation/CostDetail/put/64105c018bbc21b499f0f99d/64105c018bbc21b499f0f99e/64105c258bbc21b499f0f9a1
Content-Type: application/json
//Authorization: admin admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzA4YmM3MzA4NmJmYmIzNDQxZDNlNCIsImlhdCI6MTY3NTczNTAxMCwiZXhwIjoxNjc1NzQxNDEwfQ.scN6d8whKvzWwl0G95cQteITNug2BTj-aQ61GqypF_0

{
  "NameCost": "Chi phí Van chuyen 1 Update",
  "Units": "Phòng",
  "UnitPrice": 3000000,
  "Quantity_days": 1,
  "Quantity_times": 1,
  "IntoMoney": 0,
  "Note": "Ghi chu"
}

### Get ImplementationCost by idcontract
### API access: /api/forms/implementation-cost/:idcontract
### Test: ok
GET http://localhost:5000/api/forms/implementations/6402f614416c1d823c301cc0


### Xoa 1 chi phi trong giai doan chi phi  trien khai
### access public
###ok
DELETE  http://localhost:5000/api/forms/implementations/stages_implementation/CostDetail/delete/64105c018bbc21b499f0f99d/64105c018bbc21b499f0f99e/64105d96b6d7a1b53f42641d
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ



//============================================ 14-2






