### ok 
### LOGIN
POST http://103.88.121.45:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}



### Get all Contract 
### access private
###ok
GET http://103.88.121.45:5000/api/forms/contract


### Get all  ImplementationCost
### access public
###ok
GET http://103.88.121.45:5000/api/forms/implementation-cost

### KHOI TAO 1 CHI TRIEN KHAI
// Create ImplementationCost Voi _id.contract truyen vao
// URL access: POST http://localhost:5000/api/forms/implementation-cost/GeneralExpense/post/:idcontract
// access public
POST http://103.88.121.45:5000/api/forms/implementation-cost/post/63c09408ed60f11521b0087f
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzA5MzhmZWQ2MGYxMTUyMWIwMDg3NSIsImlhdCI6MTY3MzgzMDMwMywiZXhwIjoxNjczODM2NzAzfQ.rCcG8J8svtJelTkt1GOAotImXWm43P7ES4l1OosEElI

{
  "GeneralExpense": "Chi phí chung",
  "StagesImplementation": "Giai đoạn 1"
}

### Add 1 Object (
// Create ImplementationCost -> GeneralExpense
// URL access: POST http://localhost:5000/api/forms/implementation-cost/GeneralExpense/post/:idcontract
// access public
POST http://localhost:5000/api/forms/implementation-cost/GeneralExpense/post/63c08c08b1a40f0ce190d6e1
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjIzNmVkYWFlNTA5NGNkN2YxZWU4MyIsImlhdCI6MTY3MjY5NjUzNiwiZXhwIjoxNjcyNzAyOTM2fQ.8KC8VHWvnorrUCsJ7P-lmNpMa53XUIg0Kbh6Dbq8p-4

{
  "Content": "Chi Phi chung"
}

###
// Create ImplementationCost -> StagesImplementation
// URL access: POST http://localhost:5000/api/forms/implementation-cost/stages-implementation/post/
// access public
// them ?????????????????? giai doạn cho chi phi giai doan
POST http://localhost:5000/api/forms/implementation-cost/stages-implementation/post/63c08c08b1a40f0ce190d6e1
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjIzNmVkYWFlNTA5NGNkN2YxZWU4MyIsImlhdCI6MTY3MjY5NTExMywiZXhwIjoxNjcyNzAxNTEzfQ.fR7wbUFfT_LlT__Ytg1lVrlSLUrLuAN8t2Tr_itiMpA

{
  "Content": "Giai Doan 1"
}

###
// AddCostDetail cho chi phi chung
// URL access: POST http://localhost:5000/api/forms/implementation-cost/GeneralExpense/post
// access public

POST http://103.88.121.45:5000/api/forms/implementation-cost/general-expense/post/
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzA5MzhmZWQ2MGYxMTUyMWIwMDg3NSIsImlhdCI6MTY3MzgzMDMwMywiZXhwIjoxNjczODM2NzAzfQ.rCcG8J8svtJelTkt1GOAotImXWm43P7ES4l1OosEElI

{
  "NameCost": "Chi phí vận chuyển",
  "Units": "Phòng",
  "UnitPrice": 20000000,
  "Quantity_days": 1,
  "Quantity_times": 1,
  "IntoMoney": 0,
  "Note": "Ghi chu",
  "ImplementationCost_Id": "63c4a016eff90d4fe121c465",
  "ContentCostId": "63c4a016ce506562a374cb0f"
}

###
// AddCostDetailStage cho chi phi giai doan
// URL access: POST http://localhost:5000/api/forms/implementation-cost/stages-implementation/post
// access public

POST http://103.88.121.45:5000/api/forms/implementation-cost/stages-implementation/post
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzA5MzhmZWQ2MGYxMTUyMWIwMDg3NSIsImlhdCI6MTY3MzgzMDMwMywiZXhwIjoxNjczODM2NzAzfQ.rCcG8J8svtJelTkt1GOAotImXWm43P7ES4l1OosEElI

{
  "NameCost": "Chi phí đi lại",
  "Units": "",
  "UnitPrice": 100000,
  "Quantity_days": 1,
  "Quantity_times": 4,
  "IntoMoney": 0,
  "Note": "",
  "ImplementationCost_Id": "63c4a016eff90d4fe121c465",
  "ContentCostId": "63c4a016ce506562a374cb0e"
}


###
// Update stages-implementation Costs cho chi phi giai doan
// URL access: http://localhost:5000/api/forms/implementation-cost/stages-implementation/put/:idCosts
//Input Condition : 
//            _id: ImplementationCost_Id,
//            "GeneralExpense._id": ContentCostId,
//            "GeneralExpense.Costs._id": req.params.id
// access public

PUT http://localhost:5000/api/forms/implementation-cost/stages-implementation/put/63c29a5a7fb4c6dfcaef0298
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYmZmNTI1ZjMyODc0YWM3NTU1YzhiYSIsImlhdCI6MTY3MzU2MDkxNiwiZXhwIjoxNjczNTY3MzE2fQ.IZ6BsFXeg1aOoAl9vdoFJOQM1qVHL9EmeaNh4YtcZIk

{
  "NameCost": "Chi phí tiếp khách update",
  "Units": "Phong",
  "UnitPrice": 9000000,
  "Quantity_days": 1,
  "Quantity_times": 4,
  "IntoMoney": 0,
  "Note": "Ghi chu",
  "ImplementationCost_Id": "63c298a930ae9167f8f6e592",
  "ContentCostId": "63c298a97fb4c6dfcaef028a"
}

###
// Update Cost General Expense cho chi phi chung
// URL access: http://localhost:5000/api/forms/implementation-cost/general-expense/put/:idCosts
//Input Condition : 
//            _id: ImplementationCost_Id,
//            "GeneralExpense._id": ContentCostId,
//            "GeneralExpense.Costs._id": req.params.id
// access public

PUT http://localhost:5000/api/forms/implementation-cost/general-expense/put/63c29a5a7fb4c6dfcaef0298
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYmZmNTI1ZjMyODc0YWM3NTU1YzhiYSIsImlhdCI6MTY3MzU2MDkxNiwiZXhwIjoxNjczNTY3MzE2fQ.IZ6BsFXeg1aOoAl9vdoFJOQM1qVHL9EmeaNh4YtcZIk

{
  "NameCost": "Chi phí tiếp khách update",
  "Units": "Phong",
  "UnitPrice": 9000000,
  "Quantity_days": 1,
  "Quantity_times": 4,
  "IntoMoney": 0,
  "Note": "Ghi chu",
  "ImplementationCost_Id": "63c298a930ae9167f8f6e592",
  "ContentCostId": "63c298a97fb4c6dfcaef028a"
}

### Get ImplementationCost by id Implementation
### access public
###ok
GET http://localhost:5000/api/forms/implementation-cost/63b3570f391b9a0052aff0ce
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ

### Get ImplementationCost by IdContract
### access public
###ok
GET http://localhost:5000/api/forms/implementation-cost/contract/63b352b29fd7cd536585b9e7
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ


### Get all Contract tạo bởi user đăng nhập
### access public
###ok
DELETE  http://localhost:5000/api/forms/implementation-cost/delete/63c298a930ae9167f8f6e592
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ
