### ok 
### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}
### Get all Contract 
### API access: /api/forms/contract
### Test: ok
//GET http://103.88.121.45:5000/api/forms/contract
GET http://localhost:5000/api/forms/contract

### Create auxiliary-cost
### access Public
### Test : ok
POST http://localhost:5000/api/forms/auxiliary-cost/post/63c08c08b1a40f0ce190d6e1
Content-Type: application/json
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5MDM1OSwiZXhwIjoxNjcxMzc2NzU5fQ.4WKjVO2EpJrYhAs9L38YaB4kl-P6t4D58HbDDOUXMCU

{
  "Plan": 2
}

### Update Revenue in AuxiliaryCost by idcontract
### access Public
### Test : ok
PUT http://localhost:5000/api/forms/auxiliary-cost/put/63c08c08b1a40f0ce190d6e1


### Update Plan in AuxiliaryCost by idcontract
### access Public
### Test : ok
PUT http://localhost:5000/api/forms/auxiliary-cost/put/plan/63c08c08b1a40f0ce190d6e1
Content-Type: application/json
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5MDM1OSwiZXhwIjoxNjcxMzc2NzU5fQ.4WKjVO2EpJrYhAs9L38YaB4kl-P6t4D58HbDDOUXMCU

{
  "Plan": 1
}


### Add Cost to auxiliary-Listcost by idcontract
### access Public
### Test : ok
POST http://localhost:5000/api/forms/auxiliary-cost/post/cost/63c08c08b1a40f0ce190d6e1
Content-Type: application/json
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5MDM1OSwiZXhwIjoxNjcxMzc2NzU5fQ.4WKjVO2EpJrYhAs9L38YaB4kl-P6t4D58HbDDOUXMCU

{
  "Content": "Chi phi 3",
  "Cost": 0.03,
  "Note": "IDHD 63c08c08b1a40f0ce190d6e1"
}

### Update Cost in ListCost by idcontract/idcost
### access Public
### Recheck : ok
PUT http://localhost:5000/api/forms/auxiliary-cost/put/cost/63c08c08b1a40f0ce190d6e1/63f83687dcb5b1e75486acf8
Content-Type: application/json
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5MDM1OSwiZXhwIjoxNjcxMzc2NzU5fQ.4WKjVO2EpJrYhAs9L38YaB4kl-P6t4D58HbDDOUXMCU

{
  "Content": "Chi phi 3 updated",
  "Cost": 0.05,
  "Note": "HD Update"
}



### Get all auxiliary-cost
### access public
###ok
GET http://localhost:5000/api/forms/auxiliary-cost
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ

### Get auxiliary by id_auxiliary
### access public
###ok
GET http://localhost:5000/api/forms/auxiliary-cost/63f81da142f7f8f6a19f3436
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ

### Get auxiliary-cost by idContract
### access public
###ok
GET http://localhost:5000/api/forms/auxiliary-cost/contract/63c08c08b1a40f0ce190d6e1
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ


### Delete auxiliary-cost by id_auxiliary
### access public
###Retest: ok
DELETE  http://localhost:5000/api/forms/auxiliary-cost/delete/63f8318d42f7f8f6a1aa5b9b
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ

### Delete auxiliary-cost by id_contract
### access public
###Retest: ok
DELETE  http://localhost:5000/api/forms/auxiliary-cost/delete/contract/63c08c08b1a40f0ce190d6e1
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ


### Update Cost in ListCost by idcontract/idcost
### access Public
### Recheck : coding
DELETE  http://localhost:5000/api/forms/auxiliary-cost/delete/contract/63c08c08b1a40f0ce190d6e1/63f838e8ee1d28e840fcd822

//==== old ======================================== 

