###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "CE",
  "email": "CE@gmail.com",
  "password": "bcrypt.hashSync(req.body.password, 8)",
  "roles[]":"CEO"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "CE",
  "password": "bcrypt.hashSync(req.body.password, 8)"
}

###

GET http://localhost:5000/api/users
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOTAxNWM1NmYyYjMyM2FlY2QwOGEyOCIsImlhdCI6MTY3MDM4NzM0NCwiZXhwIjoxNjcwNDczNzQ0fQ.e6RofcyonodQ7vifa7snKWqnt7ycEuyGr8c5dcEymk4

###

PUT http://localhost:5000/api/users/638f1825915d3f41e45d229e
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhmMTgyNTkxNWQzZjQxZTQ1ZDIyOWUiLCJpYXQiOjE2NzAzMjMwMDd9.2LnfC9zLc42tocLoZGxyVrFMW4xGH_mOpRwusDoriq4

{
  "username": "hon",
  "password": "135"
}


###

DELETE http://localhost:5000/api/users/638f1825915d3f41e45d229e
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhmMTgyNTkxNWQzZjQxZTQ1ZDIyOWUiLCJpYXQiOjE2NzAzMjMwMDd9.2LnfC9zLc42tocLoZGxyVrFMW4xGH_mOpRwusDoriq4

