### ok 
### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Create MandayCost
### access Public
### Not ok
POST http://localhost:5000/api/forms/product-cost/post
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjYyOTcwMTg3OGFmMTg2NGVhOGMxNSIsImlhdCI6MTY3MzA1OTIyNiwiZXhwIjoxNjczMDY1NjI2fQ.r8jOYfbpL1t2LM8fb4p2k30XYQ_OFTkLeWbZfGH30qU

{
  "ProductName": "Server X60 IBM HD02",
  "Quantity": 10,
  "EX_W": 1, 
  "FOBCost": 2500, 
  "RatioUSD": 24000,
  "InputPrice": 50000,
  "OutputPrice": 100000,
  "InputIntoMoney": 500000,
  "OutputIntoMoney": 700000,
  "Insurance": 1,
  "Incentive": 100000,
  "Note": "A",
  "ContractID": "HD04"
}
### Get all MandayCost
### access public
###ok
GET http://localhost:5000/api/forms/product-cost
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ

### Get MandayCost by id
### access public
###ok
GET http://localhost:5000/api/forms/product-cost/63a69fc3d96b6250abaa4f7a
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ

### Get MandayCost by ContractID
### access public
###ok
GET http://localhost:5000/api/forms/product-cost/contract/63c08c08b1a40f0ce190d6e1
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ


### update MandayCost
### access Public
###  
PUT http://localhost:5000/api/forms/manday-cost/put/63a54823564e1d18b4bc1cd5
Content-Type: application/json
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5MDM1OSwiZXhwIjoxNjcxMzc2NzU5fQ.4WKjVO2EpJrYhAs9L38YaB4kl-P6t4D58HbDDOUXMCU

{
"RatioUSD": 24000,
"Department": "Phòng GP An Toàn TT Update",
"Cost": 60,
"StaffNumber": 1,
"ImplementationDay": 15,
"Note": "A",
"ContractID":"HD01"
}


### Get all Contract tạo bởi user đăng nhập
### access public
###ok
DELETE  http://localhost:5000/api/forms/manday-cost/delete/63b8dbc3165f143e28359f5b
//Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTI5NTQwMiwiZXhwIjoxNjcxMzgxODAyfQ.qtLt4F50GDz8olkKMJriYvEvFAavyIxazYzIyRuorcQ
