### ok 
### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Create User
### access Public
### Not ok -- Postman ok
POST http://localhost:5000/api/users/insertUser
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTQzNzkwMiwiZXhwIjoxNjcxNTI0MzAyfQ.QK7nwJ8nQLXYbSuDzBD_CISQbbfjHdrMrbAuqOIJED8

{
"username": "Director",
"email": "Directorn@gmail.com",
"password": "123",
"roles[]": "Directorss"
}

### Get all users public
### access public
###ok
GET http://localhost:5000/api/users/getAllUsers

### Get all users phai login
### access private
###ok
GET http://localhost:5000/api/users/view
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTQzNjE4MywiZXhwIjoxNjcxNTIyNTgzfQ.12vWIr1Yrlr0fmeLwfiajkg0ZrL-ujQBuAGOvbI9QmM

### Get user login
### access private
###ok
GET http://localhost:5000/api/users/login
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTQzNjE4MywiZXhwIjoxNjcxNTIyNTgzfQ.12vWIr1Yrlr0fmeLwfiajkg0ZrL-ujQBuAGOvbI9QmM

### Get users By RoleId
### access private
###ok
GET http://localhost:5000/api/users/ByRole
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTQzNjE4MywiZXhwIjoxNjcxNTIyNTgzfQ.12vWIr1Yrlr0fmeLwfiajkg0ZrL-ujQBuAGOvbI9QmM



###
### Update User By Id
### access Public
### Not ok -- Postman ok
POST http://localhost:5000/api/users/insertUser
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTQzNzkwMiwiZXhwIjoxNjcxNTI0MzAyfQ.QK7nwJ8nQLXYbSuDzBD_CISQbbfjHdrMrbAuqOIJED8

{
"username": "admin",
"email": "admin@gmail.com",
"password": "123",
"roles[]": "admins"
}


### Delete User By Id
### access private
### Not ok -- Postman ok
DELETE http://localhost:5000/api/users/deleteUser/63a13f58a7a2e64a0a8bf4f5
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWMyYjEyMjFiNjk2YmVkNTQyOTEyZSIsImlhdCI6MTY3MTQzNjE4MywiZXhwIjoxNjcxNTIyNTgzfQ.12vWIr1Yrlr0fmeLwfiajkg0ZrL-ujQBuAGOvbI9QmM
